### ISSUE TITLE
Unable to clone oob/master from github.com/Digilent/Eclypse-Z7

### ISSUE THREAD

**Issue by ramadhanafif** [Digilent/Eclypse-Z7-HW#2]
Current git clone example
`git clone --recursive https://github.com/Digilent/Eclypse-Z7 -b <demo branch>`

For oob/master
`git clone --recursive https://github.com/Digilent/Eclypse-Z7-HW -b oob/master`

**Comment by PhantomMachine** [comment]
Can you share the terminal output when you attempt to clone the branch?
